[bot]
server: localhost
chat_id: 1787073119
bot_token: 5088208467:AAF4BgLdiTEJfA-wXOuBpkc-TVWwQ60rftc


[camera]
host: http://localhost:8080/?action=stream
fps: 30
flip_vertically: false
flip_horizontally: false
video_duration: 10

[progress_notification]
percent: 25
time: 1800

